### ISSUE TITLE
[Feature Request] Hide Homebrew Launcher

### ISSUE THREAD

**Issue by Destiny1984** [dimok789/homebrew_launcher#13]
Please add an option to hide the Homebrew Launcher.

It doesn't make too much sense to run it from within itself.

Or maybe you could add an option to hide any app by adding something like a "visible" tag to meta.xml

**Comment by piratesephiroth** [comment]
yeah I was about top request the same.

**Comment by wildgoosespeeder** [comment]
As far as I know, homebrew on the Wii U is in its rudimentary stages. It's not going to have substantial features and sophistication as say The Homebrew Channel for Wii does. I'm sure the developers are aware of this and will have something better but that will come much later.

**Comment by Clownacy** [comment]
https://github.com/dimok789/homebrew_launcher/blob/master/src/menu/HomebrewWindow.cpp#L60

There is actually code for this, but it's dummied-out.

**Comment by Destiny1984** [comment]
Yes, i've seen the code. But it doesn't work as it should.

It hides the HomebrewLauncher, but leaves a hole in the list.

**Comment by dimok789** [comment]
Done in v1.3.
