### ISSUE TITLE
UI Glitches on Boot (caused by mishandling of hidden Mac files)

### ISSUE THREAD

**Issue by CreeperMario** [dimok789/homebrew_launcher#15]
Hello, there.
Probably a really obvious bug, but there seems to be a really weird UI glitch that occurs when I launch HBL. (See attachments for a picture).
This issue can be temporarily resolved by switching to the second page, but what if there isn't a second page to switch to?
Thanks in advance, CreeperMario.

This is right after launching HBL:
![1 - on hbl launch](https://cloud.githubusercontent.com/assets/15356475/15606364/ea56716a-244a-11e6-9d84-4fb1983f9e49.jpg)
This is after switching to the second screen (R button), and then switching back to the first (L button):
![2 - after flipping screens](https://cloud.githubusercontent.com/assets/15356475/15606368/f54aed58-244a-11e6-930c-e0278b757906.jpg)

Firmware: 5.5.1E (PAL, A.K.A Europe)
Wii U: 8GB White Model
Homebrew Launcher Version: 1.2 RC3

**Comment by dimok789** [comment]
This should be fixed. Can you confirm and close this issue if so?

**Comment by CreeperMario** [comment]
I can't seem to replicate the issue anymore. 😠 Guess something happened on Apple's side of things.
The issue could be bypassed anyway by using HBAS and avoiding macOS entirely. 😄

**Comment by dimok789** [comment]
Yeah ok. But this sorting issue you had. Its fixed. I saw the same screen when a file was being loaded but didnt load correctly. So i am closing this.
