### ISSUE TITLE
Problem compiling rpx with latest libmad (and maybe dkppc r28)

### ISSUE THREAD

**Issue by mariogamer2** [dimok789/homebrew_launcher#23]
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/6.2.0/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/libogc/lib/wii/libmad.a(frame.o): relocation R_PPC_EMB_SDA21 cannot be used when making a shared object
/opt/devkitpro/libogc/lib/wii/libmad.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

**Comment by dimok789** [comment]
Use the portslibs from the release page.

**Comment by dimok789** [comment]
Ah I think it conflicts with the one in your libogc. I forgot to remove search for libraries on the libogc path from the makefile of ELF version. Libogc is now not required at all.

**Comment by mariogamer2** [comment]
I was thinking so too,thank for pointing me on it.

**Comment by dimok789** [comment]
Done.
