### ISSUE TITLE
Installed HBL channel does not work

### ISSUE THREAD

**Issue by Leseratte10** [dimok789/homebrew_launcher#26]
I have used Haxchi to boot Sigpatcher2Sysmenu to remove the signaure checks, and have then installed the most recent Homebrew Launcher Channel 2.1 using WUP Installer Mod. The Homebrew Launcher shows up in the system menu but does only lead to a black screen. Did I do something wrong? How can I install the Homebrew Launcher correctly using Haxchi?

**Comment by CreeperMario** [comment]
I had this on my first launch attempt, but all subsequent launches have been flawless for me.
Try it a few more times and if it still freezes, I will provide instructions on how to provide your system logs.

**Comment by Leseratte10** [comment]
I tried starting it twice before reporting the bug, and tried another four times just now. Start console, start Haxchi / Sigpatch2Sysmenu, start HBL channel. Every time the console freezes with a black screen and I have to turn it off.

**Comment by Leseratte10** [comment]
Tried using Mocha instead of Sigpatcher2Sysmenu to remove the signature checks and the channel now works, so I'll just use that. I guess Sigpatcher doesn't remove all the checks.
