### ISSUE TITLE
[Problem] I am unable to get this to compile successfully

### ISSUE THREAD

**Issue by cspencer49519** [dimok789/homebrew_launcher#30]
Greetings, I am admittedly not an expert on this stuff, but I'm having an issue. I can not get this, or loadiine to compile, receiving the same error:

graffix@wiiu-dev ~/Desktop/homebrew_launcher $ make
main.cpp
In file included from /home/graffix/Desktop/homebrew_launcher/src/system/AsyncDeleter.h:21:0,
                 from /home/graffix/Desktop/homebrew_launcher/src/gui/GuiElement.h:37,
                 from /home/graffix/Desktop/homebrew_launcher/src/gui/Gui.h:20,
                 from /home/graffix/Desktop/homebrew_launcher/src/menu/MainWindow.h:22,
                 from /home/graffix/Desktop/homebrew_launcher/src/Application.h:20,
                 from /home/graffix/Desktop/homebrew_launcher/src/main.cpp:2:
/home/graffix/Desktop/homebrew_launcher/src/system/CThread.h: In constructor 'CThread::CThread(int, int, int, CThread::Callback, void*)':
/home/graffix/Desktop/homebrew_launcher/src/system/CThread.h:45:37: error: invalid conversion from 'int (*)(int, void*)' to 's32 (*)(s32, void*) {aka long int (*)(long int, void*)}' [-fpermissive]
             OSCreateThread(pThread, &CThread::threadCallback, 1, this, (u32)pThreadStack+iStackSize, iStackSize, iPriority, iAttributes);
                                     ^~~~~~~~
/home/graffix/Desktop/homebrew_launcher/Makefile:179: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
Makefile:141: recipe for target 'build' failed
make: *** [build] Error 2

Is there anything I can do to get this to compile successfully? I believe I have installed all the prerequisites. I am on Linux Mint 18 Cinnamon.

**Comment by Maschell** [comment]
You need to compile it with devkitpro r27Am 11.04.2017 22:27 schrieb Craig Spencer <notifications@github.com>:Greetings, I am admittedly not an expert on this stuff, but I'm having an issue. I can not get this, or loadiine to compile, receiving the same error:
graffix@wiiu-dev /Desktop/loadiine_gx2 $ make
main.cpp
In file included from /home/graffix/Desktop/loadiine_gx2/src/system/AsyncDeleter.h:21:0,
from /home/graffix/Desktop/loadiine_gx2/src/gui/GuiElement.h:37,
from /home/graffix/Desktop/loadiine_gx2/src/gui/Gui.h:20,
from /home/graffix/Desktop/loadiine_gx2/src/menu/MainWindow.h:22,
from /home/graffix/Desktop/loadiine_gx2/src/Application.h:20,
from /home/graffix/Desktop/loadiine_gx2/src/main.cpp:2:
/home/graffix/Desktop/loadiine_gx2/src/system/CThread.h: In constructor 'CThread::CThread(int, int, int, CThread::Callback, void*)':
/home/graffix/Desktop/loadiine_gx2/src/system/CThread.h:45:37: error: invalid conversion from 'int ()(int, void)' to 's32 ()(s32, void) {aka long int ()(long int, void)}' [-fpermissive]
OSCreateThread(pThread, &CThread::threadCallback, 1, this, (u32)pThreadStack+iStackSize, iStackSize, iPriority, iAttributes);
^
/home/graffix/Desktop/loadiine_gx2/Makefile:191: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
Makefile:146: recipe for target 'build' failed
make: *** [build] Error 2
Is there anything I can do to get this to compile successfully? I believe I have installed all the prerequisites. I am on Linux Mint 18 Cinnamon.

**Comment by cspencer49519** [comment]
Wow, huge derp on my part. Thanks.
