### ISSUE TITLE
Error -3

### ISSUE THREAD

**Issue by Grandzelda** [dimok789/homebrew_launcher#38]
Hey when i added a new homebrew to my apps folder (or install folder for WUP installer) upon launching homebrew launcher with Haxchi on v5.5.2 it just displays `-3` and nothing else.
any help appreciated

**Comment by Grandzelda** [comment]
nvm it fixed itself after a second try

**Comment by Maschell** [comment]
-3 Means it was unable to mount a SD Card. Make sure that's a FAT32 SDCard is inserted

(anwser for people who find this issue)
