### ISSUE TITLE
cant launch Homebrew_launcher

### ISSUE THREAD

**Issue by tarooxi** [dimok789/homebrew_launcher#42]
If I launch over the webiste laodiine.ovh it says could  not load file 
wiiu/apps/homebrew_launcher/fomebrew_launcher.elf 

help would be nice
Thanks
-Tari

**Comment by CreeperMario** [comment]
Is `homebrew_launcher.elf` actually on your SD card?

**Comment by tarooxi** [comment]
Yes it is and it worked out now

Thanks

~tari
