### ISSUE TITLE
HBL 2.1 loading but not showing apps

### ISSUE THREAD

**Issue by racpore** [dimok789/homebrew_launcher#43]
I am using CBHC with HBL 2.1 and it was previously working with no problems, however now when I boot into the HBL channel it loads and shows the version number at the bottom right but all of the apps like wup installer and loadiine are missing. I checked my sd card and all of the required files are present in sd/wiiu/apps. Any help would be appreciated

**Comment by CreeperMario** [comment]
Try loading HBL from the web browser or Haxchi directly. I found that, if there were issues mounting the SD card or reading its filesystem, the channel version ignores those errors and displays a blank menu, like what you're experiencing. If the Haxchi/browser version of HBL fails to mount the SD card, error messages are displayed.

**Comment by racpore** [comment]
Reinstalling the latest nightly of Loadiine onto the sd card seems to have resolved the problem.
