### ISSUE TITLE
Stuck in white screen with wii u logo

### ISSUE THREAD

**Issue by jbmyre** [dimok789/homebrew_launcher#44]

**Comment by CreeperMario** [comment]
This usually happens when the meta.xml or icon.png file for one of the apps on your SD card became corrupted somehow.

To solve this, delete and re-install programs one-by-one until the problem is resolved.

**Comment by jbmyre** [comment]
wdym delete and install them 1 by 1

**Comment by jbmyre** [comment]
can u maybe send me some non corrupted loadiine gx2 and homebrew launcher files

**Comment by CreeperMario** [comment]
[Homebrew Launcher](https://github.com/dimok789/homebrew_launcher/releases/tag/1.4) and [Loadiine GX2](https://github.com/dimok789/loadiine_gx2/releases) release pages.

**Comment by RobertoD91** [comment]
same issues, i tried also with another sd card, with only homebrew laucher

**Comment by RobertoD91** [comment]
solved reformatting sd card with "sdformatter" from sdcard.org
