### ISSUE TITLE
Autostart elf or additional controls?

### ISSUE THREAD

**Issue by Kekskruemel** [dimok789/homebrew_launcher#7]
Hi,

same problem as posted some months ago for loadiine from me.
I play wii u remote with capture card and addition controller emulation software.

Marshall has released HID to vpad, so after running this I can control and play nearly all with my emulated controller. But there is no way for me to run the elf in the homebrew launcher menu from remote.

Maybe you can add some more controls like wii remote controls ? After adding this to loadiine I was able to control the menu with my harmony smart hub from remote.

Or adding an autostart option to the homebrew launcher ?

Thx for your work.

**Comment by dimok789** [comment]
Yeah this can be done but let's do this for another release some other time.

**Comment by Kekskruemel** [comment]
No rush.

Thx for the help.

**Comment by dimok789** [comment]
Actually I just checked HBL and wii remote control is added already but I think what you want is D-PAD controls right?

**Comment by Kekskruemel** [comment]
Found out that elf's send by sendelf autostart. So I doesn't need the autostart feature or dpad control feature, but if you have the time, maybe dpad control would be useful for someone else.

Thx for your work!
